spring:
  application:
    name: microservice3
  zipkin:
    base-url: http://zipkin-server/
  sleuth:
    enabled: true
    sampler:
      percentage: 1
server:
  port: 8883
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/